version: '3'
services:
  db:
    build:
      context: ./MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: golang_db
    ports:
      - "3306:3306"
    networks:
      - backend
  app:
    build:
      context: ./Go
    volumes:
      - "./Go:/go/src/app"
    container_name: golang_app
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - frontend
      - backend
    depends_on:
      - db
  frontend:
    build:
      context: ./Frontend
    container_name: website_fe
    volumes:
      - "./Frontend/public-html/:/usr/local/apache2/htdocs/"
    ports:
      - "4000:80"
    networks:
      - frontend
    depends_on:
      - app
      - db
    tty: true

networks:
  backend:
  frontend: