CREATE DATABASE websitedb;
USE websitedb;
CREATE TABLE contacts (
id INT AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(50) NOT NULL DEFAULT "none",
LAST_NAME VARCHAR(50) NOT NULL DEFAULT "none",
PHONE INT,
EMAIL VARCHAR(255) NOT NULL DEFAULT "none",
PCM VARCHAR(1) NOT NULL DEFAULT "E",
HDUHAU VARCHAR(2) NOT NULL DEFAULT "TV",
COMMENTS VARCHAR(280)
);